name: 'Action Image Resize'
description: 'Compress PNG, JPG, JPEG, and WebP images to AVIF, resize to max 2560px width and updates Markdown references'
author: 'RainPPR'
inputs:
  path:
    description: 'The directory to process (relative to the repository root). Defaults to the entire repository.'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'image'
  color: 'blue'
